export const portfolio = [
  {
    name: "the Walt Disney Company",
    description: [
      "Maintenance, debug and development",
    ],
    responsibilities: [
      "Complex component creation, documentation and debugging",
      "Content Assets, Content slots, Custom objects and Templates management",
      "Implementing, documenting and debugging third-party services",
      "Knowledge-sharing and support for new team members",
      "Always an active part of discussions regarding the best way to develop and change components when it comes to accessibility and usability",
      "Also responsible for the investigation of new stacks and sharing knowledge on some proof of concepts using PWA on SFCC (with OCAPI) and highly cached pages for specific projects",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA, Ocapi, PWA, ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
      "React",
    ],
    address: "https://www.shopdisney.com",
    image: "www.shopdisney.com_.png",
  },
  {
    name: "Saks OFF 5TH",
    description: ["Debugging and maintenance"],
    responsibilities: [
      "Post-deploy support, from ISML to configurations",
      "Solving issues in both Front and Backend",
      "Working close to the QA team",
      "Knowledge-sharing and support for new team members",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://www.saksoff5th.com/",
    image: "www.saksoff5th.com_.png",
  },
  {
    name: "YETI",
    description: ["Debugging and maintenance"],
    responsibilities: [
      "Post-deploy support, from ISML to configurations",
      "Solving issues in both Front and Backend",
      "Working close to the QA team",
      "Knowledge-sharing and support for new team members",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://www.yeti.com",
    image: "www.yeti.com_.png",
  },
  {
    name: "theOrdinary",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Developing and documenting complex components",
      "Developing PLPs, PDPs, Menu, etc",
      "Handling data and content entering",
      "Implementing third-party services",
      "Knowledge-sharing and support for new team members",
      "Dealing with creative requests",
      "theOrdinary, Niod and Hylamide were part of the Deciem umbrella - and they each follow some specific styles and easter-eggs through the website",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://theordinary.com",
    image: "theordinary.com_en-br.png",
  },
  {
    name: "NIOD",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Developing and documenting complex components",
      "Developing PLPs, PDPs, Menu, etc",
      "Handling data and content entering",
      "Implementing third-party services",
      "Knowledge-sharing and support for new team members",
      "Dealing with creative requests",
      "theOrdinary, Niod and Hylamide were part of the Deciem umbrella - and they each follow some specific styles and easter-eggs through the website",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://niod.com/",
    image: "niod.com_en-br.png",
  },
  {
    name: "Deciem",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Developing and documenting complex components",
      "Developing PLPs, PDPs, Menu, etc",
      "Handling data and content entering",
      "Implementing third-party services",
      "Knowledge-sharing and support for new team members",
      "Dealing with creative requests",
      "theOrdinary, Niod and Hylamide were part of the Deciem umbrella - and they each follow some specific styles and easter-eggs through the website",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://deciem.com/",
    image: "deciem.com_en-br.png",
  },
  {
    name: "Acana Petfood",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Content-assets creation",
      "Entering content",
      "Component development and documentation",
      "Implementing third-party services",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://acana.com/en",
    image: "www.acana.com_en-US_homepage.png",
  },
  {
    name: "Orijen Petfood",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Content-assets creation",
      "Entering content",
      "Component development and documentation",
      "Implementing third-party services",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://orijenpetfoods.com/en",
    image: "www.orijenpetfoods.com_en-US_homepage.png",
  },
  {
    name: "Champions Petfood",
    description: [
      "First project using Salesforce Commerce Cloud",
      "Part of the Development Team from start to finish",
    ],
    responsibilities: [
      "Content-assets creation",
      "Entering content",
      "Component development and documentation",
      "Implementing third-party services",
    ],
    tech: "SFCC",
    techDetails: [
      "Salesforce Commerce Cloud",
      "SFRA",
      "ISML",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance",
      "XML",
    ],
    address: "https://championpetfoods.com/en",
    image: "championpetfoods.com_en.png",
  },
  {
    name: "Raid Vietnam",
    description: ["Legacy code maintenance and debugging"],
    responsibilities: [
      "Improving and refactoring legacy code",
      "Constant debugging",
      "Dealing with different languages, internationalization and writing systems",
      "Component development and documentation",
      "Implementing third-party services",
    ],
    tech: "Sitecore",
    techDetails: ["Sitecore", "Razor, C#", "HTML, CSS, JS", "SASS"],
    address: "https://www.raid.vn/vi-vn",
    image: "www.raid.vn_vi-vn.png",
  },
  {
    name: "SCJohnson",
    description: ["Worked on many brands under the SCJ client"],
    responsibilities: [
      "Improving and refactoring legacy code",
      "Constant debugging",
      "Dealing with different languages, internationalization and writing systems",
      "Component development and documentation",
      "Implementing third-party services",
    ],
    tech: "Sitecore",
    techDetails: ["Sitecore", "Razor, C#", "HTML, CSS, JS", "SASS"],
    address: "https://www.scjohnson.com/en/",
    image: "www.scjohnson.com_en.png",
  },
  {
    name: "Advisian",
    description: ["Project Redesign"],
    responsibilities: [
      "Redesign for the main website sections",
      "Component development and documentation",
    ],
    tech: "Sitecore",
    techDetails: ["Sitecore", "Razor, C#", "HTML, CSS, JS", "SASS"],
    address: "https://www.advisian.com/",
    image: "www.advisian.com_en_.png",
  },
  {
    name: "BLG",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Component development and documentation",
      "Implementing third-party services",
      "Constantly under pressure, as the deadline wasn't properly set and the scope would suffer drastic changes on a weekly basis",
      "Successful delivery though",
    ],
    tech: "Sitecore",
    techDetails: [
      "Sitecore",
      "Coveo, Razor",
      "C#",
      "HTML, CSS, JS, SASS",
      "GDPR and ADA Compliance, jQuery",
    ],
    address: "https://www.blg.com/en",
    image: "www.blg.com_en.png",
  },
  {
    name: "General Mills",
    description: ["Legacy support", "Debugging"],
    responsibilities: [
      "Constant debugging",
      "Improving and refactoring legacy code",
      "Development of new components",
    ],
    tech: "Sitecore",
    techDetails: ["Sitecore", "Razor, C#", "HTML, CSS, JS, jQuery, SASS"],
    address: "https://generalmills.com/",
    image: "www.generalmills.com_.png",
  },
  {
    name: "Amica Senior Lifestyles",
    description: ["Part of the Development Team from start to finish"],
    responsibilities: [
      "Component development and documentation",
      "Debugging",
      "Part of discussions for improvement",
    ],
    tech: "Sitecore",
    techDetails: ["Sitecore", "Razor, C#", "HTML, CSS, JS, jQuery, SASS"],
    address: "https://www.amica.ca/",
    image: "www.amica.ca_.png",
  },
  {
    name: "Navico",
    description: ["Customer Portal Development"],
    responsibilities: ["Development and documentation of Customer Portal"],
    techDetails: ["Episerver", "Razor, C#", "HTML, CSS, JS", "SASS"],
    tech: "Episerver",
    address: "https://navico.com/",
    image: "www.navico.com_.png",
  },
  {
    name: "YahSat",
    description: [
      "First project using Sitecore",
      "Website Development",
      "Initial planning",
    ],
    responsibilities: [
      "Part of the initial sprints",
      "Components development and documentation",
    ],
    techDetails: ["Sitecore", "Razor, C#", "HTML, CSS, JS, jQuery, SASS"],
    tech: "Sitecore",
    address: "https://yahsat.com/",
    image: "www.yahsat.com_.png",
  },
  {
    name: "Brookfield",
    description: ["Website Maintenance", "Bugfixing"],
    responsibilities: ["Late change requests", "Frontend Debugging"],
    techDetails: ["HTML, CSS, JS, jQuery, SASS"],
    tech: "Drupal",
    address: "https://brookfield.com/",
    image: "www.brookfield.com_.png",
  },
  {
    name: "Bayer Brasil",
    description: ["Internal system update", "UI Documentation"],
    responsibilities: [
      "Frontend update on the internal system",
      "Writing the UI Style Guide",
    ],
    techDetails: ["HTML, CSS, JS, jQuery, SASS", "FractalJS"],
    tech: "Drupal",
    address: "https://bayer.com.br/",
    image: "www.bayer.com.br_pt_.png",
  },
  {
    name: "Samsung Brasil",
    description: ["Marketing Campaigns"],
    responsibilities: [
      "Developing and deploying landing pages",
      "Developing e-mail marketing campaigns",
      "Integration between landing pages and e-mail databases",
      "Handling segmentation, reports, analytics, data configuration and automation on Salesforce Marketing Cloud",
    ],
    techDetails: [
      "Salesforce Marketing Cloud",
      "HTML, CSS, JS, jQuery",
      "Bootstrap",
    ],
    tech: "MJML",
    image: "www.samsung.com_br_.png",
  },
  {
    name: "Walmart Brasil",
    description: ["Website maintenance", "Marketing Campaigns"],
    responsibilities: [
      "Developing and deploying landing pages",
      "Developing e-mail marketing campaigns",
      "Integration between landing pages and e-mail databases",
      "Handling segmentation, reports, analytics, data configuration and automation on Salesforce Marketing Cloud",
    ],
    techDetails: [
      "Salesforce Marketing Cloud",
      "HTML, CSS, JS, jQuery",
      "Bootstrap",
    ],
    image: "walmart.png",
  },
  {
    name: "SamsClub Brasil",
    description: ["Website maintenance", "Marketing Campaigns"],
    responsibilities: [
      "Developing and deploying landing pages",
      "Developing e-mail marketing campaigns",
      "Integration between landing pages and e-mail databases",
      "Handling segmentation, reports, analytics, data configuration and automation on Salesforce Marketing Cloud",
    ],
    techDetails: [
      "Developed internal tools to improve efficiency on the mail marketing development",
      "Salesforce Marketing Cloud",
      "MJML",
      "HTML, CSS, JS, jQuery",
      "C#, Razor",
    ],
    address: "https://samsclub.com.br",
    image: "www.samsclub.com.br_.png",
  },
]
